### ISSUE TITLE
Allow searching for works and objects by works that are about or represent/depict them (from 1731)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#29]
**Problem Description:**
The advanced search does not allow for searching objects/works that are about a given object/work.

**Expected Behavior/Solution:**
Add support for searching objects/works that are about an object/work.

<ins>Per triage - may be high dev cost/time</ins>

**Requirements:**

-  Data update with these connections - relationship exists in data, but more could be added.  
-  ML advanced search configuration update - https://github.com/project-lux/lux-marklogic/issues/74
-  Update frontend

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] Backend requirements - Peter
- [ ] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**
- [Le Jardin de Daubigny](https://lux.collections.yale.edu/view/text/29b98ec5-b8c9-405e-a83f-03e2eb5a427b) is about [Daubigny's Garden](https://lux.collections.yale.edu/view/text/5ad5d97a-1b16-42c4-ad5e-145b2371643b). 
- [this text](https://lux-front-tst.collections.yale.edu/view/text/7bbd4203-95ed-4d66-b9e2-a78c23217edb) is about [Alphabet Book South Russian](https://lux-front-tst.collections.yale.edu/view/text/2bc1c5a0-0085-449f-bf60-ca685d72f128). 
- https://lux-front-tst.collections.yale.edu/view/text/7ae0fcb3-41c5-400e-be63-337b70536dff is the subject of another work (NEED TO FIND)

**Dependencies/Blocks:**
- Blocked by: https://github.com/project-lux/lux-marklogic/issues/74

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/62

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/1575

**Wireframe/Mockup:**
TBD

**Comment by kamerynB** [comment]
Update 6/14:
This issue is blocked as it requires ML configuration to be implemented. The ML issue has been prioritized for the 6/24 milestone deadline.

**Comment by roamye** [comment]
Adding this to the 09/09 milestone as the ML ticket is set to deploy in the 08/19 milestone. We can move it further out if needed.

**Comment by clarkepeterf** [comment]
@roamye I think this issue is fully solved by https://github.com/project-lux/lux-marklogic/issues/74. All of the UAT criteria can be searched for:

 - https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22aboutWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F5ad5d97a-1b16-42c4-ad5e-145b2371643b%22%7D%7D
 - https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22aboutWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F2bc1c5a0-0085-449f-bf60-ca685d72f128%22%7D%7D%5D%7D
 - https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22aboutWork%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Ftext%2F7ae0fcb3-41c5-400e-be63-337b70536dff%22%7D%7D%5D%7D

**Comment by roamye** [comment]
Propose close based on this comment: https://github.com/project-lux/lux-marklogic/issues/74#issuecomment-2305254263

**Comment by prowns** [comment]
ok to close per core team
