### ISSUE TITLE
Archival material is not sorted in Explore correctly

### ISSUE THREAD

**Issue by azaroth42** [project-lux/lux-frontend#411]
**Problem Description:**
HMOs are not sorted correctly in Explore

For example:
  https://lux-front-sbx.collections.yale.edu/data/set/7b2c542b-5741-43d0-a4ea-cc288b279447 

sorts in the wrong place in its parent:

https://lux.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447 

sort 1, 10, 100, 101 etc 

**Expected Behavior/Solution:**
It should sort according to sort value, which is padded to six 0s

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

https://lux.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447  

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
@azaroth42 - so, for example, instead of `FHS/3/1/100 ` it should display as:  `FHS/3/1/000100`?

which comes from the lines: 

```
"type": "Identifier",
"content": "FHS/3/1/000100",
"assigned_by": [
{
"type": "AttributeAssignment",
"motivated_by": [
{
"id": "https://lux-front-sbx.collections.yale.edu/data/set/1b1e6ec4-b01e-4f48-a0f1-e98f489ea280",
"type": "Set"
}
]
}
],
```

**Comment by kamerynB** [comment]
@clarkepeterf @azaroth42 The [current HAL link](https://lux-front-sbx.collections.yale.edu/api/search/work?q=%7B%22partOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F1b1e6ec4-b01e-4f48-a0f1-e98f489ea280%22%7D%7D&sort=workArchiveSortId:asc) returns a sorted list of results. These are also not HumanMadeObjects but Sets (I'm not sure if I'm reading the original comment correctly). I can't find anything on the frontend that would indicate it is sorting the values after it makes the API call.

**Comment by clarkepeterf** [comment]
@azaroth42 @kamerynB 

Current PRD and SBX:
 - They are sorted wrong because the index for archive sort id uses the following AAT: http://vocab.getty.edu/aat/300451544 (sort title) - the sort identifiers with his AAT do not have prepended 0s.

In DEV and TST:
 - They are sorted correctly, because the index for archive sort id is updated to use the following AAT: http://vocab.getty.edu/aat/300456575 (sort value)
 - See correctly sorted archive here: https://lux-front-tst.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447

SBX and DATA-DEV:
 - are set to have their indexes updated tonight (so should sort correctly in the morning).

PRD:
 - is not scheduled to have indexes updated until the Blue-Green switch on 10/28.

This index was updated this deployment as part of https://github.com/project-lux/lux-marklogic/issues/325

**Comment by roamye** [comment]
ticket forming: 
- displayed correctly but sorted incorrectly. sort value changes with the data. SBX has correct AAT. 
- is correctly displayed now. 
- proposing close. Has to wait until the release. All environments work correctly besides PROD.

**Comment by roamye** [comment]
approved by UAT to close.
